Make delete function
yoroduyaken/blog-crud pull request #39
Opened 2023-01-10 13:43 UTC by yoroduyaken

#17 

close #17 

レビューして欲しい内容
不要なブログが削除されるかどうか

2023-01-10 13:48 UTC, Sunasuna24 requested changes
1点FBあります！

2023-01-10 13:48 UTC, Sunasuna24 commented on routes/web.php
> +Route::get('/blogs/{id}', [BlogController::class, 'show'])->name('blogs.delete');
BlogControllerの`show`メソッドって他の場所でも使っていなかったでしたっけ？

2023-01-11 12:20 UTC, yoroduyaken commented on routes/web.php
> +Route::get('/blogs/{id}', [BlogController::class, 'show'])->name('blogs.delete');
使用しています。
blogs.showのところです。

2023-01-11 12:36 UTC, Sunasuna24 commented on routes/web.php
> +Route::get('/blogs/{id}', [BlogController::class, 'show'])->name('blogs.delete');
> 使用しています。

なるほどです！

「削除機能」と「編集機能」で同じメソッドを使用する感じですか？？

2023-01-11 12:43 UTC, yoroduyaken commented on routes/web.php
> +Route::get('/blogs/{id}', [BlogController::class, 'show'])->name('blogs.delete');
メソッドは分けたいのですが、一覧表示に削除ボタンがあった方が
使いやすいのではないかと考えてblogs.showにした流れです。

通常だとどのようにしているかを本と検索した記事で見ていますが、
まだ、理解しきれていません。

2023-01-11 13:18 UTC, closed without merging