Make blog page
yoroduyaken/blog-crud pull request #7
Opened 2022-11-10 12:31 UTC by yoroduyaken

#4 

close#4

レビューして欲しい内容
`/blog`にてブログページが表示されるかどうか。

2022-11-10 13:48 UTC, Sunasuna24 requested changes
細かいFBをしたので、対応よろしくお願いします！🙏

2022-11-10 13:48 UTC, Sunasuna24 commented on resources/views/blog.blade.php
> +    <textarea name="tarea3" cols="30" rows="3" maxlength="1000"
`name="tarea3"`は分かりづらいので、変更しましょう！

2022-11-10 13:48 UTC, Sunasuna24 commented on resources/views/blog.blade.php
> +    <input type="text" name="text" placeholder="題名を入力してください。">
`name="text"`の名前を変更しましょう！

2022-11-11 11:33 UTC, yoroduyaken commented on resources/views/blog.blade.php
> +    <textarea name="tarea3" cols="30" rows="3" maxlength="1000"
ご指摘ありがとうございます。
修正いたしました。

2022-11-11 11:34 UTC, yoroduyaken commented on resources/views/blog.blade.php
> +    <input type="text" name="text" placeholder="題名を入力してください。">
かしこまりました。

2022-11-11 13:13 UTC, Sunasuna24 approved these changes
LGTMです！🙆‍♂️

2022-11-12 01:18 UTC, merged